# Project: Bandas Cpp
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Bandas.o
LINKOBJ  = Bandas.o
LIBS     = -L"E:/DevC++/Dev-Cpp/MinGW64/lib32" -L"E:/DevC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -L"I:/Guigui/Bandas Cpp" -L"C:/Users/Guilherme/Documents/Projetos Casuais/BandasCpp/BandasCpp" -m32
INCS     = -I"E:/DevC++/Dev-Cpp/MinGW64/include" -I"E:/DevC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/DevC++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Guilherme/Documents/Projetos Casuais/BandasCpp/BandasCpp"
CXXINCS  = -I"E:/DevC++/Dev-Cpp/MinGW64/include" -I"E:/DevC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/DevC++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/DevC++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"C:/Users/Guilherme/Documents/Projetos Casuais/BandasCpp/BandasCpp"
BIN      = BandasCpp.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Bandas.o: Bandas.cpp
	$(CPP) -c Bandas.cpp -o Bandas.o $(CXXFLAGS)
